export default {
    Text: 'Text',
    AutoCode: 'AutoCode',
    BizType: 'BizType',
    Select: 'Select',
    MultiSelect: 'MultiSelect',
    Date: 'Date',
    Time: 'Time',
    Lookup: 'Lookup',
    MultiLookup: 'MultiLookup',
    MainDetail: 'MainDetail',
    RelateCreate: 'RelateCreate',
    Boolean: 'Boolean',
    District: 'District',
    Location: 'Location',
    Integer: 'Integer',
    Real: 'Real',
    Currency: 'Currency',
    Percent: 'Percent',
    Image: 'Image',
    File: 'File',
    Expression: 'Expression',
    Aggregation: 'Aggregation',
    DynamicLookup: 'DynamicLookup',
};